version: '3.8'
services:
  calculator-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./src:/app/src
    command: sh -c "cd build && make && ./calculator"